{
	"version": 1733315384,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sprite1-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/sprite13-sheet0.png",
		"images/sprite14-sheet0.png",
		"images/sprite15-sheet0.png",
		"images/sprite16-sheet0.png",
		"images/sprite17-sheet0.png",
		"images/sprite18-sheet0.png",
		"images/tiledbackground.png",
		"media/let me tell you something.m4a",
		"media/let me tell you something.ogg",
		"media/wazup.m4a",
		"media/wazup.ogg",
		"media/no please no.m4a",
		"media/no please no.ogg",
		"media/fake news.m4a",
		"media/fake news.ogg",
		"media/damn.m4a",
		"media/damn.ogg",
		"media/my name is jeff.m4a",
		"media/my name is jeff.ogg",
		"media/boo.m4a",
		"media/boo.ogg",
		"media/yayyy.m4a",
		"media/yayyy.ogg",
		"media/bgm - meme mash.m4a",
		"media/bgm - meme mash.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"fake news.mp4",
		"wazup.mp4",
		"no please no.mp4",
		"let me tell you something.mp4",
		"damn.mp4",
		"my name is jeff.mp4"
	]
}